[package]
name = "rerp_website_ecommerce_impl"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ecommerce"
path = "src/main.rs"
doc = false

[dependencies]
rerp_website_ecommerce = { path = "../ecommerce" }
brrtrouter = { workspace = true }
brrtrouter_macros = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tikv-jemallocator = { workspace = true }
rerp_common = { path = "../../common" }

# Add your additional dependencies here
