[package]
name = "rerp_pos_payment_gateway_impl"
version = "0.1.3"
edition = "2021"

[[bin]]
name = "payment_gateway"
path = "src/main.rs"
doc = false

[dependencies]
rerp_pos_payment_gateway = { path = "../payment-gateway" }
brrtrouter = { workspace = true }
brrtrouter_macros = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tikv-jemallocator = { workspace = true }
rerp_common = { path = "../../common" }

# Add your additional dependencies here
