[package]
name = "rerp_marketing_social_media_impl"
version = "0.1.3"
edition = "2021"

[[bin]]
name = "social_media"
path = "src/main.rs"
doc = false

[dependencies]
rerp_marketing_social_media = { path = "../social-media" }
brrtrouter = { workspace = true }
brrtrouter_macros = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tikv-jemallocator = { workspace = true }
rerp_common = { path = "../../common" }

# Add your additional dependencies here
