[package]
name = "rerp_marketplace_integration_hub_impl"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "integration_hub"
path = "src/main.rs"

[dependencies]
rerp_marketplace_integration_hub = { path = "../integration-hub" }
brrtrouter = { workspace = true }
brrtrouter_macros = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tikv-jemallocator = { workspace = true }
rerp_common = { path = "../../common" }

# Add your additional dependencies here
