[package]
name = "rerp_manufacturing_production_planning_impl"
version = "0.1.1"
edition = "2021"

[[bin]]
name = "production_planning"
path = "src/main.rs"
doc = false

[dependencies]
rerp_manufacturing_production_planning = { path = "../production-planning" }
brrtrouter = { workspace = true }
brrtrouter_macros = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tikv-jemallocator = { workspace = true }
rerp_common = { path = "../../common" }

# Add your additional dependencies here
