[package]
name = "rerp_sales_subscription_impl"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "subscription"
path = "src/main.rs"

[dependencies]
rerp_sales_subscription = { path = "../subscription" }
brrtrouter = { workspace = true }
brrtrouter_macros = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tikv-jemallocator = { workspace = true }
rerp_common = { path = "../../common" }

# Add your additional dependencies here
