service:
  name: amd
  port: 8013
  containerPort: 8013
  nodePort: 31013
image:
  repository: localhost:5001
  name: rerp-amd
  tag: tilt
  pullPolicy: IfNotPresent
deployment:
  replicas: 1
  namespace: rerp
app:
  binaryName: account_management_domain_service_api
  serviceName: amd
