service:
  name: bank-sync
  port: 8005
  containerPort: 8005
  nodePort: 31005
image:
  repository: localhost:5001
  name: rerp-bank-sync
  tag: tilt
  pullPolicy: IfNotPresent
deployment:
  replicas: 1
  namespace: rerp
app:
  binaryName: bank_sync
  serviceName: bank-sync
