# Values file for Accounting BFF Service (RERP)
# BFF aggregates and proxies to accounting microservices.

service:
  name: bff
  port: 8010
  containerPort: 8010
  nodePort: 30810

image:
  repository: localhost:5001
  name: rerp-bff
  tag: tilt
  pullPolicy: IfNotPresent

deployment:
  replicas: 1
  namespace: rerp

app:
  binaryName: bff
  serviceName: bff
