service:
  name: billing
  port: 8015
  containerPort: 8015
  nodePort: 31015
image:
  repository: localhost:5001
  name: pricewhisperer-billing
  tag: tilt
  pullPolicy: IfNotPresent
deployment:
  replicas: 1
  namespace: pricewhisperer
app:
  binaryName: billing_service_api
  serviceName: billing
