service:
  name: budget
  port: 8007
  containerPort: 8007
  nodePort: 31007
image:
  repository: localhost:5001
  name: rerp-budget
  tag: tilt
  pullPolicy: IfNotPresent
deployment:
  replicas: 1
  namespace: rerp
app:
  binaryName: budget_service_api
  serviceName: budget
