service:
  name: ftebe
  port: 8011
  containerPort: 8011
  nodePort: 31011
image:
  repository: localhost:5001
  name: rerp-ftebe
  tag: tilt
  pullPolicy: IfNotPresent
deployment:
  replicas: 1
  namespace: rerp
app:
  binaryName: ftebe_testing_service_api
  serviceName: ftebe
