service:
  name: marketing
  port: 8014
  containerPort: 8014
  nodePort: 31014
image:
  repository: localhost:5001
  name: pricewhisperer-marketing
  tag: tilt
  pullPolicy: IfNotPresent
deployment:
  replicas: 1
  namespace: pricewhisperer
app:
  binaryName: marketing_service_api
  serviceName: marketing
